apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argo
spec:
  rules:
  - host: argo.cloud.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argo-server
            port: 
              name: web
